# Generated by Django 6.0.5 on 2026-05-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100, unique=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=5)),
                ('listings', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'country_code'], name='accommodati_city_ead835_idx')],
                'unique_together': {('city', 'country_code')},
            },
        ),
    ]
