# Generated by Django 6.0.5 on 2026-05-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adzuna_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('redirect_url', models.URLField(blank=True, max_length=500)),
                ('adref', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('company_display_name', models.CharField(blank=True, max_length=255)),
                ('company_raw', models.JSONField(blank=True, default=dict)),
                ('location_display_name', models.CharField(blank=True, max_length=255)),
                ('location_area', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_is_predicted', models.CharField(blank=True, max_length=10)),
                ('contract_type', models.CharField(blank=True, max_length=50)),
                ('contract_time', models.CharField(blank=True, max_length=50)),
                ('category_tag', models.CharField(blank=True, max_length=100)),
                ('category_label', models.CharField(blank=True, max_length=100)),
                ('enriched_city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('enriched_country_name', models.CharField(blank=True, max_length=100)),
                ('enriched_locality', models.CharField(blank=True, max_length=100)),
                ('enriched_principal_subdivision', models.CharField(blank=True, max_length=100)),
                ('enriched_country_code', models.CharField(blank=True, max_length=5)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enriched_city', 'enriched_country_name'], name='jobsnapshot_enriche_6ad303_idx'), models.Index(fields=['enriched_country_code'], name='jobsnapshot_enriche_6126b3_idx'), models.Index(fields=['contract_type'], name='jobsnapshot_contrac_147f15_idx'), models.Index(fields=['category_tag'], name='jobsnapshot_categor_0cfdc6_idx')],
            },
        ),
    ]
