# Generated by Django 6.0.5 on 2026-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsnapshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('listings', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
