# Generated by Django 6.0.5 on 2026-05-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsnapshot', '0002_airbnbcache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirbnbCache',
        ),
    ]
